### ISSUE TITLE
Can you share the downloaded data.

### ISSUE THREAD

**Issue by chenriwei** [xuefeng7/FACE-LIBRARY#1]
Hi, your work is very valuable，but for some reason you know :) , I can not get the image data, so , can you share the download data you have download?

Thanks in advance.

chen

**Comment by xuefeng7** [comment]
Hi, thanks. Since we have a huge amount of face, the amount of photo will be large either (approximately 36GB). Due to resource limitation, we decided not to directly store them, however, I added a full example to show how a post is retrieved. You can download them by following the example. Good luck.

**Comment by chenriwei** [comment]
Thanks for your helps~

**Comment by ysc703** [comment]
Hi, @xuefeng7 
I got the error when use the id2code.py:  urllib.error.URLError: <urlopen error [WinError 10060]
It seems that line 91 doesn't work:
url = 'https://api.instagram.com/oembed/?url=http://instagram.com/p/' + shortcode

Thanks
