### ISSUE TITLE
~29% broken images

### ISSUE THREAD

**Issue by kylemcdonald** [xuefeng7/FACE-LIBRARY#4]
I converted the image IDs into image URLs, and I've noticed that many of the images are invalid. For example `3579832224_1364722965090736174` from `face_lib_16.txt` becomes https://instagram.com/p/BLweE5fDRgu

Currently I see 91903 out of 315966 images are 404, which is around 29% of the images. Does this sound right, or am I making a mistake?

I also noticed that 56 lines in the source files are newlines, and they will cause a JSON parser to throw an error when attempting to decode them

**Comment by xuefeng7** [comment]
Hi I saw your email few days ago, and sorry for replying to you that late, I was so busy on school works. I will also answer the questions from your email here. 

1) In terms of this issue, I think if some images are deleted by the users, then you won't be able to retrieve them anymore. Also, only pid (1364722965090736174) should be fed to the converter. The amount of missing images is awful, or maybe Facebook changed their short_URL conversion protocol? But since ~70% of the images can be retrieved, I think highly possible this may not be the case.

2) for the ground truth fatigue rate dataset, yes, we have it; but first of all, you will need to get the images from NIST, and this requires some approval works. check [here](https://www.nist.gov/itl/iad/image-group/color-feret-database), and once you have this dataset, I can send you the rates for each face (by their photo_id) included in this dataset (assuming no faces added or deleted).

Hope these would be helpful.

**Comment by kylemcdonald** [comment]
Thanks! I've got Color FERET from NIST. I'm looking forward to working with the fatigue data.

**Comment by kylemcdonald** [comment]
Hi @xuefeng7 any new info available? I'd love to check out this data.
